title: The Dime 
description: The Dime
baseurl: "" # set to "/repo-name" if deploying under a subfolder
url: "http://localhost:4000" # change to your domain in production

baseurl: "/home.github.io" # the subpath of your site, e.g. /blog

sass:
  sass_dir: _sass

# Build settings
# markdown: kramdown
# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

# Exclude from build
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - _site